// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PositionMgmt.Domain.Models;

public partial class ActionMaster
{
    public int Id { get; set; }

    public string ActionType { get; set; }
}