// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PositionMgmt.Domain.Models;

public partial class SecurityPrice
{
    public long Id { get; set; }

    public long SecurityId { get; set; }

    public decimal? Price { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    public virtual SecurityMaster Security { get; set; }
}