// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PositionMgmt.Domain.Models;

public partial class SecurityMaster
{
    public long Id { get; set; }

    public string SecurityCode { get; set; }

    public string SecurityName { get; set; }

    public virtual ICollection<SecurityPrice> SecurityPrices { get; set; } = new List<SecurityPrice>();
}