// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PositionMgmt.Domain.Models;

public partial class Transaction
{
    public long TransactionId { get; set; }

    public long TradeId { get; set; }

    public long Version { get; set; }

    public int? SecurityId { get; set; }

    public int? Quantity { get; set; }

    public int? TransactionTypeId { get; set; }

    /// <summary>
    /// Only for output
    /// </summary>
    public string? TransactionType { get; set; }

    public int? ActionTypeId { get; set; }

    /// <summary>
    /// Only for output
    /// </summary>
    public string? ActionType { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifyDate { get; set; }
}